version: '3'

services:
  captcha-slover:
    container_name: captcha-1688
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - default
    ports:
      - "13000:13000"
    command: npm run start
    restart: always

networks:
  default:
    name: my-network
